- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 36000 #10 hrs # Corvax-RoleTime
#    - !type:RoleTimeRequirement
#      role: JobSecurityOfficer
#      time: 36000 #10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #50 hrs # Corvax-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 144000 #40 hrs
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      # Corvax-Wega-AprilFools-Start
      - type: Clumsy
        gunShootFailDamage:
          types:
            Blunt: 5
            Piercing: 4
          groups:
            Burn: 3
      - type: SleepEmitSound
        snore: /Audio/Voice/Misc/silly_snore.ogg
        interval: 10
      # Corvax-Wega-AprilFools-End

- type: startingGear
  id: HoSGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
