- type: gameMapPool
  id: WegaDefaultMapPool
  maps:
  # Highpop
  #- WegaKerberos Remove for Rework
  - CorvaxDelta
  - CorvaxAvrite
  - WegaCyberiad
  #- WegaCereStation
  # Midpop
  - CorvaxPaper
  - Bagel
  - Marathon
  # Lowpop
  - CorvaxSilly
  - Barratry
  - Packed
  - Meta
