- type: gameMapPool
  id: WegaDefaultMapPool
  maps:
  # Highpop ++++++++++ / April Fools
  - WegaShnake
  # Highpop
  - WegaKerberos
  #- CorvaxAvrite
  - WegaCyberiad
  - WegaCereStation
  - WegaSpectrum
  - Fland
  # Midpop
  - CorvaxPaper
  - WegaCore
  - Bagel
  - Marathon
  # Lowpop
  - CorvaxSilly
  - WegaMaus
  - Barratry
  - Packed
  - Meta
