# Vampire
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleVampire
  name: Vampire Role
#  description: mind-role-vampire-description
  components:
  - type: MindRole
    antagPrototype: Vampire
  - type: VampireRole
